/*=========================================================================================
  File Name: sidebarItems.js
  Description: Sidebar Items list. Add / Remove menu items from here.
  Strucutre:
          url     => router path
          name    => name to display in sidebar
          slug    => router path name
          icon    => Feather Icon component/icon name
          tag     => text to display on badge
          tagColor  => class to apply on badge element
          i18n    => Internationalization
          submenu   => submenu of current item (current item will become dropdown )
                NOTE: Submenu don't have any icon(you can add icon if u want to display)
          isDisabled  => disable sidebar item/group
  ----------------------------------------------------------------------------------------
  Item Name: Vuexy - Vuejs, HTML & Laravel Admin Dashboard Template
  Author: Pixinvent
  Author URL: http://www.themeforest.net/user/pixinvent
==========================================================================================*/
import globalVariable from "@/utils/globalVariable";
import $store from '@/store/store.js';

let iconPrefix = $store.getters.iconPrefix !== null ? $store.getters.iconPrefix : 'color_';
export default [
	{
		url: '/home',
		name: 'Dashboard',
		slug: 'home',
        icon: iconPrefix + 'dashboard_icon24',
        cakraIcon: true,
        isDisabled: false,
        tagOrder: globalVariable.global.accessUserMenuOrder.dashboard,
	},
	{
        url: '/reservation/availability',
        name: 'Availability',
        slug: 'availability',
        icon: iconPrefix + 'room_type_availability_icon24',
        cakraIcon: true,
        isDisabled: false,
        tagOrder: globalVariable.global.accessUserMenuOrder.availability,
    },
    {
        url: '/reservation/room-availability',
        name: 'Room Availability',
        slug: 'room-availability',
        icon: iconPrefix + 'room_availability_icon24',
        cakraIcon: true,
        tagOrder: globalVariable.global.accessUserMenuOrder.roomAvailability,
    },
    {
        url: '/reservation/guest-group',
        name: 'Guest Group',
        slug: 'guest-group',
        icon: iconPrefix + 'guest_group_icon24',
        cakraIcon: true,
        // isDisabled: true,
        tagOrder: globalVariable.global.accessUserMenuOrder.guestGroup,
    },
    {
        url: '/reservation/reservation-list',
        name: 'Reservation',
        slug: 'reservation-list',
        icon: iconPrefix + 'reservation_icon24',
        cakraIcon: true,
        isDisabled: false,
        tagOrder: globalVariable.global.accessUserMenuOrder.reservation,
    },
	{
		url: '/guestinhouse',
		name: 'Guest In House',
		slug: 'guestinhouse',
        icon: iconPrefix + 'guest_in_house_icon24',
        cakraIcon: true,
        isDisabled: false,
        tagOrder: globalVariable.global.accessUserMenuOrder.guestInHouse,
    },
    {
		url: '/master-folio',
		name: 'Master Folio',
		slug: 'master-folio',
        icon: iconPrefix + 'master_folio_icon24',
        cakraIcon: true,
        // isDisabled: true,
        tagOrder: globalVariable.global.accessUserMenuOrder.masterFolio,
    },
    {
		url: '/desk-folio',
		name: 'Desk Folio',
		slug: 'desk-folio',
        icon: iconPrefix + 'desk_folio_icon24',
        cakraIcon: true,
        // isDisabled: true,
        tagOrder: globalVariable.global.accessUserMenuOrder.deskFolio,
    },
	{
		url: '/folio-history',
		name: 'Folio History',
		slug: 'folio-history',
        icon: iconPrefix + 'folio_history_icon24',
        cakraIcon: true,
        // isDisabled: true,
        tagOrder: globalVariable.global.accessUserMenuOrder.folioHistory,
    },
	{
		url: '/housekeeping',
		name: 'House Keeping',
		slug: 'housekeeping',
        icon: iconPrefix + 'housekeeping_icon24',
        cakraIcon: true,
        // // isDisabled: true,
        tagOrder: globalVariable.global.accessUserMenuOrder.houseKeeping,
    },
    // {
    //     url: '/lost-and-found',
    //     name: 'Lost and Found',
    //     slug: 'lost-and-found',
    //     icon: iconPrefix + 'lost_and_found_icon24',
    //     cakraIcon: true,
    //     // isDisabled: true,
    //     tagOrder: globalVariable.global.accessUserMenuOrder.lostAndFound,
    // },
    {
		url: '/cashier-report',
		name: 'Cashier Report',
		slug: 'cashier-report',
        icon: iconPrefix + 'cashier_report_icon24',
        cakraIcon: true,
        // isDisabled: true,
        tagOrder: globalVariable.global.accessUserMenuOrder.cashierReport,
    },
    {
		url: '',
		name: 'Night Audit',
		slug: 'night-audit',
        icon: iconPrefix + 'dayend_close_icon24',
        cakraIcon: true,
		submenu: [
            {
                url: '/night-audit/auto-post-transaction',
                name: 'Auto Post Transaction',
                slug: 'auto-post-transaction',
                icon: iconPrefix + 'UsersIcon',
                // // isDisabled: true,
                tagOrder: globalVariable.global.accessUserMenuOrder.autoPostTransaction,
            },
            {
                url: '/night-audit/dayend-close',
                name: 'Dayend Close',
                slug: 'dayend-close',
                icon: iconPrefix + 'UsersIcon',
                // // isDisabled: true,
                tagOrder: globalVariable.global.accessUserMenuOrder.dayendClose,
            }
        ]
    },

    // Marketing
    // {
    //     url: '/marketing/phone_book',
    //     name: 'Phone Book',
    //     slug: 'phone-book',
    //     icon: iconPrefix + 'phone_book_icon24',
    //     cakraIcon: true,
    //     // isDisabled: true,
    //     tagOrder: globalVariable.global.accessUserMenuOrder.phoneBook
    // },
    {
		url: '',
		name: 'Back Office',
		slug: '',
		icon: 'TrendingUpIcon',
        // isDisabled: globalVariable.global.accessUserMenuOrder.arCityLedger || globalVariable.global.accessUserMenuOrder.arCityLedgerInvoice,
		submenu: [
            {
                url: '/back-office/ap/refund',
                name: 'AP Refund Deposit',
                slug: 'ap-refund',
                icon: iconPrefix + 'ap_refund_icon24',
                cakraIcon: true,
                // isDisabled: true,
                tagOrder: globalVariable.global.accessUserMenuOrder.apRefundDeposit,
            },
            {
                url: '/back-office/ap/commission-other',
                name: 'AP Commission & Other',
                slug: 'ap-commission-other',
                icon: iconPrefix + 'ap_commission_icon24',
                cakraIcon: true,
                // isDisabled: true,
                tagOrder: globalVariable.global.accessUserMenuOrder.apCommissionAndOther,
            },
            {
                url: '/back-office/ar/city-ledger',
                name: 'AR City Ledger',
                slug: 'ar-city-ledger',
                icon: iconPrefix + 'ar_city_ledger_icon24',
                cakraIcon: true,
                // isDisabled: true,
                tagOrder: globalVariable.global.accessUserMenuOrder.arCityLedger,
            },
            {
                url: '/back-office/ar/city-ledger-invoice',
                name: 'AR City Ledger Invoice',
                slug: 'ar-city-ledger-invoice',
                icon: iconPrefix + 'ar_city_ledger_invoice_icon24',
                cakraIcon: true,
                // isDisabled: true,
                tagOrder: globalVariable.global.accessUserMenuOrder.arCityLedgerInvoice,
            },
            {
                url: '/back-office/ar/bank-transaction',
                name: 'Bank Transaction',
                slug: 'ar-bank-transaction',
                icon: iconPrefix + 'bank_transaction_icon24',
                cakraIcon: true,
                // isDisabled: true,
                tagOrder: globalVariable.global.accessUserMenuOrder.bankTransaction,
            },
            {
                url: '/back-office/receipt',
                name: 'Receipt',
                slug: 'receipt',
                // icon: iconPrefix + 'receipt_icon24',
                icon: iconPrefix + 'UsersIcon',
                // cakraIcon: true,
                // isDisabled: true,
                tagOrder: globalVariable.global.accessUserMenuOrder.receipt,
            },
            {
                url: '/back-office/ar/bank-reconciliation',
                name: 'Bank Reconciliation',
                slug: 'ar-bank-reconciliation',
                icon: iconPrefix + 'bank_reconciliation_icon24',
                cakraIcon: true,
                // isDisabled: true,
                tagOrder: globalVariable.global.accessUserMenuOrder.bankReconciliation,
            },
            {
                url: '/back-office/budget/income',
                name: 'Income Budget',
                slug: 'income-budget',
                icon: iconPrefix + 'bank_reconciliation_icon24',
                cakraIcon: true,
                // isDisabled: true,
                tagOrder: globalVariable.global.accessUserMenuOrder.incomeBudget,
            },
    //         {
    //             url: '/back-office/budget/statistic',
    //             name: 'Budget Statistic',
    //             slug: 'budget-statistic',
    //             icon: iconPrefix + 'bank_reconciliation_icon24',
    //             cakraIcon: true,
    //             // isDisabled: true,
    //             tagOrder: globalVariable.global.accessUserMenuOrder.budgetStatistic,
    //         },
    // //         {
    // //             url: '/back-office/export-jurnal',
    // //             name: 'Export Jurnal',
    // //             slug: 'export-jurnal',
    // //             icon: iconPrefix + 'UsersIcon',
    // //         },
        ]
    },
    // {
    //     url: '',
    //     name: 'Tools',
    //     slug: 'tools',
    //     icon: iconPrefix + 'configuration_icon24',
    //     cakraIcon: true,
    //     submenu: [

        {
            url: '',
            name: 'Configuration',
            slug: 'configuration',
            icon: iconPrefix + 'SettingsIcon',
            tagOrder: globalVariable.global.accessUserMenuOrder.configuration,
            submenu: [
                {
                    url: '/configuration/company_information',
                    name: 'Company Information',
                    slug: 'configuration-company-information',
                    icon: iconPrefix + 'GridIcon',
                    // isDisabled: true,
                },
                {
                    url: '/configuration/global_parameter',
                    name: 'Global Parameter',
                    slug: 'configuration-global-parameter',
                    icon: iconPrefix + 'GridIcon',
                    // isDisabled: true,
                },
                {
                    url: '/configuration/reservation2',
                    name: 'Reservation 2',
                    slug: 'configuration-reservation-2',
                    icon: iconPrefix + 'GridIcon',
                    // isDisabled: true,
                },
                {
                    url: '',
                    name: 'Reservation 1',
                    slug: 'configuration-reservation-1',
                    icon: iconPrefix + 'ChevronsDownIcon',
                    // isDisabled: true,
                    submenu: [{
                        url: '/configuration/reservation1/roomtype',
                        name: 'Room Type',
                        slug: 'configuration-reservation1-roomtype',
                        icon: iconPrefix + 'FileIcon',
                        // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/room',
                            name: 'Room',
                            slug: 'configuration-reservation1-room',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/package',
                            name: 'Package',
                            slug: 'configuration-reservation1-package',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/bedtype',
                            name: 'Bed Type',
                            slug: 'configuration-reservation1-bedtype',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/roomview',
                            name: 'Room View',
                            slug: 'configuration-reservation1-roomview',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/roomrate',
                            name: 'Room Rate',
                            slug: 'configuration-reservation1-roomrate',
                            icon: iconPrefix + 'FileIcon',
                            // // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/dynamicrate',
                            name: 'Dynamic Rate',
                            slug: 'configuration-reservation1-dynamicrate',
                            icon: iconPrefix + 'FileIcon',
                            // // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/lastdeal',
                            name: 'Last Deal',
                            slug: 'configuration-reservation1-lastdeal',
                            icon: iconPrefix + 'FileIcon',
                            // // isDisabled: true,
                        },
    //                     {
    //                         url: '/configuration/reservation1/room_amenities',
    //                         name: 'Room Amenities',
    //                         slug: 'configuration-reservation1-room_amenities',
    //                         icon: iconPrefix + 'FileIcon',
    //                         // isDisabled: true,
    //                     },
    //                     {
    //                         url: '/configuration/reservation1/owner',
    //                         name: 'Owner',
    //                         slug: 'configuration-reservation1-owner',
    //                         icon: iconPrefix + 'FileIcon',
    //                         // isDisabled: true,
    //                     },
    //                     {
    //                         url: '/configuration/reservation1/roomrate_category',
    //                         name: 'Room Rate Category',
    //                         slug: 'configuration-reservation1-roomrate_category',
    //                         icon: iconPrefix + 'FileIcon',
    //                         // isDisabled: true,
    //                     },
    //                     {
    //                         url: '/configuration/reservation1/roomrate_subcategory',
    //                         name: 'Room Rate Sub Category',
    //                         slug: 'configuration-reservation1-roomrate_subcategory',
    //                         icon: iconPrefix + 'FileIcon',
    //                         // isDisabled: true,
    //                     },
                        {
                            url: '/configuration/reservation1/room_unavailable_reason',
                            name: 'Room Unavailable Reason',
                            slug: 'configuration-reservation1-room_unavailable_reason',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/roomboy',
                            name: 'Room Boy',
                            slug: 'configuration-reservation1-roomboy',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/title',
                            name: 'Guest Title',
                            slug: 'configuration-reservation1-title',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/guest_type',
                            name: 'Guest Type',
                            slug: 'configuration-reservation1-guest_type',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/country',
                            name: 'Country',
                            slug: 'configuration-reservation1-country',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/state',
                            name: 'State',
                            slug: 'configuration-reservation1-state',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/nationality',
                            name: 'Nationality',
                            slug: 'configuration-reservation1-nationality',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/language',
                            name: 'Language',
                            slug: 'configuration-reservation1-language',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/idcardtype',
                            name: 'ID Card Type',
                            slug: 'configuration-reservation1-idcardtype',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/payment_type',
                            name: 'Payment Type',
                            slug: 'configuration-reservation1-payment_type',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/market_category',
                            name: 'Market Category',
                            slug: 'configuration-reservation1-market_category',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/market',
                            name: 'Market',
                            slug: 'configuration-reservation1-market',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/marketing',
                            name: 'Marketing',
                            slug: 'configuration-reservation1-marketing',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/card_bank',
                            name: 'Card Bank',
                            slug: 'configuration-reservation1-card_bank',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/card_type',
                            name: 'Card Type',
                            slug: 'configuration-reservation1-card_type',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
    //                     {
    //                         url: '/configuration/reservation1/loan_item',
    //                         name: 'Loan Item',
    //                         slug: 'configuration-reservation1-loan_item',
    //                         icon: iconPrefix + 'FileIcon',
    //                         // isDisabled: true,
    //                     },
                        {
                            url: '/configuration/reservation1/credit_card_charge',
                            name: 'Credit Card Charge',
                            slug: 'configuration-reservation1-credit_card_charge',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
                        {
                            url: '/configuration/reservation1/phone_book_type',
                            name: 'Phone Book Type',
                            slug: 'configuration-reservation1-phone_book_type',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                        },
    //                     // {
    //                     //     url: '/configuration/reservation1/member_point_type',
    //                     //     name: 'Member Point Type',
    //                     //     slug: 'configuration-reservation1-member_point_type',
    //                     //     icon: iconPrefix + 'FileIcon',
    //                     //     // isDisabled: true,
    //                     // },
    //                     // {
    //                     //     url: '/configuration/reservation1/member_outlet_discount',
    //                     //     name: 'Member Outlet Discount',
    //                     //     slug: 'configuration-reservation1-member_outlet_discount',
    //                     //     icon: iconPrefix + 'FileIcon',
    //                     //     // isDisabled: true,
    //                     // },
    //                     // {
    //                     //     url: '/configuration/reservation1/member',
    //                     //     name: 'Member',
    //                     //     slug: 'configuration-reservation1-member',
    //                     //     icon: iconPrefix + 'FileIcon',
    //                     //     // isDisabled: true,
    //                     // },
    //                     // {
    //                     //     url: '/configuration/reservation1/voucher_reason',
    //                     //     name: 'Voucher Reason',
    //                     //     slug: 'configuration-reservation1-voucher_reason',
    //                     //     icon: iconPrefix + 'FileIcon',
    //                     //     // isDisabled: true,
    //                     // },
    //                     {
    //                         url: '/configuration/reservation1/competitor_category',
    //                         name: 'Competitor Category',
    //                         slug: 'configuration-reservation1-competitor_category',
    //                         icon: iconPrefix + 'FileIcon',
    //                         // isDisabled: true,
    //                     },
    //                     {
    //                         url: '/configuration/reservation1/competitor',
    //                         name: 'Competitor',
    //                         slug: 'configuration-reservation1-competitor',
    //                         icon: iconPrefix + 'FileIcon',
    //                         // isDisabled: true,
    //                     },
                    ]
                },{
                    url: '',
                    name: 'User Setting',
                    slug: 'user-setting',
                    icon: iconPrefix + 'UserIcon',
                    submenu: [{
                            url: '/configuration/usersetting/user',
                            name: 'Users',
                            slug: 'configuration-usersetting-user',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                            tagOrder: globalVariable.global.accessUserMenuOrder.user,
                    },
                        {
                            url: '/configuration/usersetting/usergroup',
                            name: 'User Group',
                            slug: 'configuration-usersetting-usergroup',
                            icon: iconPrefix + 'FileIcon',
                            // isDisabled: true,
                            tagOrder: globalVariable.global.accessUserMenuOrder.userGroup,
                        }]
                    },
            ]
        },

        {
            url: '/back-office/report',
            name: 'Report',
            slug: 'report',
            icon: iconPrefix + 'report_icon24',
            cakraIcon: true,
            // isDisabled: true,
            tagOrder: globalVariable.global.accessUserMenuOrder.report,
        },

    // ]
// },

];
